# This file was generated by the tap Cask workflow. DO NOT EDIT.
cask "cfl" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "806849205714b0c069b9ef519ee6420eb32c5396e2bce73a3b5be2de38489609"
      url "https://github.com/addozhang/confluence-cli/releases/download/v#{version}/cfl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d751d8d17cd09c582f9d092165f6645229bae0461fe586caf160f070f8f3d3d"
      url "https://github.com/addozhang/confluence-cli/releases/download/v#{version}/cfl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a74f5e98bb7db8236e9e619cdfca4a0a58d4dc4b2333cbefcf04eb7449d2742"
      url "https://github.com/addozhang/confluence-cli/releases/download/v#{version}/cfl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e025fb20d35e302768b2828ce247475c162af16aa3eb7aa75e3997a8c725980d"
      url "https://github.com/addozhang/confluence-cli/releases/download/v#{version}/cfl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cfl"
  desc "URL-native Confluence Server/DC CLI"
  homepage "https://github.com/addozhang/confluence-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfl"

  # No zap stanza required
end
