# This file was generated by GoReleaser. DO NOT EDIT.
cask "jk" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "fab222545c4a9026f12139d4213963d6c26ae2d00ef3522f31ead413a7e71720"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f30dc209d117abf77c0cb42334fad27fd761d621a479b1922d03548bd1be2ce2"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6e39c930940769d655ab53e8e7baad469ebdfd5e16d31ac452d6e78e08652c4"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "14285cab7de9ea10414f6e35fb833cba184d286b4cb2c779e3852534a70fc926"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jk"
  desc "Pipeline-native Jenkins CLI"
  homepage "https://github.com/addozhang/jk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jk"

  # No zap stanza required

end
