# This file was generated by GoReleaser. DO NOT EDIT.
cask "jk" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "5528c5746e671b2e8f6de0dce9838602a6963ca0745415ea4fab421ddf17d346"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a8598b194dd1d299a98f669818fda2dc2a9a843b5bd36fb969e28d5ecd4a034a"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "36dab12ee6e1a131fdfe22c0987d5442c26a112a93aee70a5a918950ba031050"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "151399220109552688fe9996fd903484fc17063211f12fc9a1b0c7cdf20f507b"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jk"
  desc "Pipeline-native Jenkins CLI"
  homepage "https://github.com/addozhang/jk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jk"

  # No zap stanza required
end
