# This file was generated by GoReleaser. DO NOT EDIT.
cask "jk" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "e074308475c881a5ae3644e3b4e2d2e126ae5094cacedfafe9ff3e0e1aa3592c"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe6c3904681231f7a9077ce0e5c735a038886d68e4a03d06248deb9851555706"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c29266f2a61c9bf2b5057c74cc986bd84e46fc7f5ace7ea2347b5e231fd1fc49"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2094958b9a22c6a71a6ceae517710b7c3578a1c889a2e3d317a6b9cb0d80b14e"
      url "https://github.com/addozhang/jk/releases/download/v#{version}/jk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jk"
  desc "Pipeline-native Jenkins CLI"
  homepage "https://github.com/addozhang/jk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jk"

  # No zap stanza required
end
