# This file was generated by the tap Cask workflow. DO NOT EDIT.
cask "jr" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "aa978b4132e77ad2fce92c024f7e7600f1e39c829b949840dc12c20e1bd989cd"
      url "https://github.com/addozhang/jira-cli/releases/download/v#{version}/jr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f57fee5a1833933896157df919c69c480f820eb2d682e63fd5099f930ef282e"
      url "https://github.com/addozhang/jira-cli/releases/download/v#{version}/jr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "121eebe531869b0e24a1808ecd14a7a0c58693dbec217573fa7dd42bb27cebcd"
      url "https://github.com/addozhang/jira-cli/releases/download/v#{version}/jr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b6a505ded3b73fc03e46f10dc15bc520f55cb2e03acc10dbaec00f2722136f6"
      url "https://github.com/addozhang/jira-cli/releases/download/v#{version}/jr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jr"
  desc "URL-native Jira Server / Data Center CLI"
  homepage "https://github.com/addozhang/jira-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jr"

  # No zap stanza required
end
