# This file was generated by the tap Cask workflow. DO NOT EDIT.
cask "nx" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "df2403d1b17e9222a9aa1e33237b7974c495b9640c04d8af0f9c537f839955f7"
      url "https://github.com/addozhang/nexus-cli/releases/download/v#{version}/nx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03eb1eaa81864a79eebfd6de974d6b80bb1f6f9225593cca00e56aa7c1e12e03"
      url "https://github.com/addozhang/nexus-cli/releases/download/v#{version}/nx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c4b67c9f80ae9227ef2f4d45651dc4faba9cdee5e8ce513832c25f2a1eb4da43"
      url "https://github.com/addozhang/nexus-cli/releases/download/v#{version}/nx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "43d6d9c260f92962ed05f15ddb5fae4d63f7bffdef6711dc0b53db13ce586889"
      url "https://github.com/addozhang/nexus-cli/releases/download/v#{version}/nx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nx"
  desc "Read-only query CLI for Sonatype Nexus Repository 3"
  homepage "https://github.com/addozhang/nexus-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nx"

  # No zap stanza required
end
