# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfl < Formula
  desc "URL-native Confluence Server/DC CLI"
  homepage "https://github.com/addozhang/confluence-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.3.0/cfl_0.3.0_darwin_amd64.tar.gz"
      sha256 "3d751d8d17cd09c582f9d092165f6645229bae0461fe586caf160f070f8f3d3d"

      define_method(:install) do
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.3.0/cfl_0.3.0_darwin_arm64.tar.gz"
      sha256 "806849205714b0c069b9ef519ee6420eb32c5396e2bce73a3b5be2de38489609"

      define_method(:install) do
        bin.install "cfl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.3.0/cfl_0.3.0_linux_amd64.tar.gz"
      sha256 "e025fb20d35e302768b2828ce247475c162af16aa3eb7aa75e3997a8c725980d"
      define_method(:install) do
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.3.0/cfl_0.3.0_linux_arm64.tar.gz"
      sha256 "9a74f5e98bb7db8236e9e619cdfca4a0a58d4dc4b2333cbefcf04eb7449d2742"
      define_method(:install) do
        bin.install "cfl"
      end
    end
  end

  test do
    system "#{bin}/cfl", "version"
  end
end
