# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfl < Formula
  desc "URL-native Confluence Server/DC CLI"
  homepage "https://github.com/addozhang/confluence-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.0/cfl_0.2.0_darwin_amd64.tar.gz"
      sha256 "c7bd6331693b5be51c5ee550024299d0cfadf9f6a29a4556f54b2ac60a75cdff"

      define_method(:install) do
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.0/cfl_0.2.0_darwin_arm64.tar.gz"
      sha256 "f9708033d164040fa72c860d12385cdf95d2db2e5d037d4c53ed0367a541d8d3"

      define_method(:install) do
        bin.install "cfl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.0/cfl_0.2.0_linux_amd64.tar.gz"
      sha256 "e7b4f645fe5acbd44622de1d032487d909e6a5fda37405d10a39df7dcd2b3af4"
      define_method(:install) do
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.0/cfl_0.2.0_linux_arm64.tar.gz"
      sha256 "d00d287b83be1fabaa282ebdc3e0a26148fcddc85ce9544c1f7c0a44aadc7ce5"
      define_method(:install) do
        bin.install "cfl"
      end
    end
  end

  test do
    system "#{bin}/cfl", "version"
  end
end
