# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfl < Formula
  desc "URL-native Confluence Server/DC CLI"
  homepage "https://github.com/addozhang/confluence-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.1/cfl_0.2.1_darwin_amd64.tar.gz"
      sha256 "352c5f8662d96f0ce530baf8b8ca89c4ba617787b234272d39aa168834a00201"

      define_method(:install) do
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.1/cfl_0.2.1_darwin_arm64.tar.gz"
      sha256 "16819ef36d5d959826b0607ca48f23acc7185dd86b81d594de3e71792fe5a043"

      define_method(:install) do
        bin.install "cfl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.1/cfl_0.2.1_linux_amd64.tar.gz"
      sha256 "98cb872396318cd0f808b9c8963124936507153a17edc9a5ed9b3d23ca79e268"
      define_method(:install) do
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/confluence-cli/releases/download/v0.2.1/cfl_0.2.1_linux_arm64.tar.gz"
      sha256 "70a73d26e973e6e0cc74fce82c0cabf20fc48ab8f4c31bd158e2d01bff9dbb1f"
      define_method(:install) do
        bin.install "cfl"
      end
    end
  end

  test do
    system "#{bin}/cfl", "version"
  end
end
