# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jk < Formula
  desc "Pipeline-native Jenkins CLI"
  homepage "https://github.com/addozhang/jk"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/addozhang/jk/releases/download/v0.1.0/jk_0.1.0_darwin_amd64.tar.gz"
      sha256 "a78aafbe1dc5a1d8d3578cff6af57b64859e28a1065f2021275d88f9f8438bb2"

      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/addozhang/jk/releases/download/v0.1.0/jk_0.1.0_darwin_arm64.tar.gz"
      sha256 "9e293d50ca48724fc5c27d37917d8b9530a82bf10ac05ff98745208cd34a731c"

      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/jk/releases/download/v0.1.0/jk_0.1.0_linux_amd64.tar.gz"
      sha256 "8fbeffbbc6541175eb57fe4d1e54ca61b1d23a34e1c1ef0de3846a9401446c52"
      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/jk/releases/download/v0.1.0/jk_0.1.0_linux_arm64.tar.gz"
      sha256 "a4de82d09314c9612e6f441c8bf04713fc112863411d7400114d4ff02bc2cdf2"
      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  test do
    system "#{bin}/jk", "version"
  end
end
