# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jk < Formula
  desc "Pipeline-native Jenkins CLI"
  homepage "https://github.com/addozhang/jk"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/addozhang/jk/releases/download/v0.4.0/jk_0.4.0_darwin_amd64.tar.gz"
      sha256 "3966232eb9f2bfeb65f8c7424f6898b179be44805dfcef24e3b22520bef8c9f5"

      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/addozhang/jk/releases/download/v0.4.0/jk_0.4.0_darwin_arm64.tar.gz"
      sha256 "9912edb76f7115ec630d64f6b44a3f19b6f7f626f13d552d0db47de123a42bf4"

      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/jk/releases/download/v0.4.0/jk_0.4.0_linux_amd64.tar.gz"
      sha256 "e0624b8b4e2c5ee451c770686f4d51dd9efd746520bebe900679506cb3a30f32"
      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/jk/releases/download/v0.4.0/jk_0.4.0_linux_arm64.tar.gz"
      sha256 "43501b629ab299885cb0f683935e364a8da4e8f5e32a5e62070aaf1233e6ad69"
      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  test do
    system "#{bin}/jk", "version"
  end
end
