# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jk < Formula
  desc "Pipeline-native Jenkins CLI"
  homepage "https://github.com/addozhang/jk"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/addozhang/jk/releases/download/v0.2.0/jk_0.2.0_darwin_amd64.tar.gz"
      sha256 "c2b1b6c7a175dddab2a2b1dceb859a5d156940aea6bd86c46dac900b25db498b"

      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/addozhang/jk/releases/download/v0.2.0/jk_0.2.0_darwin_arm64.tar.gz"
      sha256 "ce266f44f0c93e52ba936d42c263ff0f9a5e17988189612c194bed3df91c6aa3"

      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/jk/releases/download/v0.2.0/jk_0.2.0_linux_amd64.tar.gz"
      sha256 "cefdac9d4503b0aebb95b5bf66e0ec9ab9d2362a23846f269620b9112892dedb"
      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/addozhang/jk/releases/download/v0.2.0/jk_0.2.0_linux_arm64.tar.gz"
      sha256 "563a7fd50e3fc1a2b6cd5b4a0990cf909bde8c9e928061a7df3ff8cbbb28ba19"
      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  test do
    system "#{bin}/jk", "version"
  end
end
